drop table if exist book;

create table book(
    id bigint GENERATED BY DEFAULT AS IDENTITY not null,
    isbn varchar(255),
    publisher varchar(255),
    title varchar(255),
    authorId bigint,
    primary key (id)
) engine=InnoDB;

