version: "3.8"
services:
  database:
    image: mysql
    container_name: database
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - database.env
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql-volume: