DROP TABLE IF EXISTS applicationdb2;
DROP USER IF EXISTS 'dbadmin'@'%';
DROP USER IF EXISTS 'dbuser'@'%';
CREATE DATABASE IF NOT EXISTS applicationdb2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'dbadmin'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON 'applicationdb2'.* TO 'dbadmin'@'%';
CREATE USER IF NOT EXISTS 'dbuser'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON 'applicationdb2'.* TO 'dbuser'@'%';
FLUSH PRIVILEGES;